# Generated by Django 6.1 on 2026-10-02 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilbioteca', '0002_comuna_estado_genero_idioma_provincia_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comuna',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comuna',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='pais',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pais',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='region',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='region',
            name='updated_at',
        ),
    ]
