# Generated by Django 6.1 on 2026-10-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilbioteca', '0003_remove_comuna_created_at_remove_comuna_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.CharField(max_length=60, verbose_name='Región'),
        ),
    ]
